# Generated by Django 5.0.6 on 2024-06-07 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('officecode', models.CharField(db_column='officeCode', max_length=10, primary_key=True, serialize=False, verbose_name='辦公室代碼')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('phone', models.CharField(max_length=50, verbose_name='電話')),
                ('addressline1', models.CharField(db_column='addressLine1', max_length=50, verbose_name='地址1')),
                ('addressline2', models.CharField(blank=True, db_column='addressLine2', max_length=50, null=True, verbose_name='地址2')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='州')),
                ('country', models.CharField(max_length=50, verbose_name='國家')),
                ('postalcode', models.CharField(db_column='postalCode', max_length=15, verbose_name='郵遞區號')),
                ('territory', models.CharField(max_length=10, verbose_name='區域')),
            ],
            options={
                'db_table': 'offices',
            },
        ),
        migrations.CreateModel(
            name='Productlines',
            fields=[
                ('productline', models.CharField(db_column='productLine', max_length=50, primary_key=True, serialize=False, verbose_name='產品線')),
                ('textdescription', models.CharField(blank=True, db_column='textDescription', max_length=4000, null=True, verbose_name='描述')),
                ('htmldescription', models.TextField(blank=True, db_column='htmlDescription', null=True, verbose_name='其他描述')),
                ('image', models.TextField(blank=True, null=True, verbose_name='圖片')),
            ],
            options={
                'db_table': 'productlines',
            },
        ),
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'permissions': [('can_view_customers', 'Can view customers'), ('can_view_employees', 'Can view employees'), ('can_view_offices', 'Can view offices')],
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employeenumber', models.IntegerField(db_column='employeeNumber', primary_key=True, serialize=False, verbose_name='員工編號')),
                ('lastname', models.CharField(db_column='lastName', max_length=50, verbose_name='姓氏')),
                ('firstname', models.CharField(db_column='firstName', max_length=50, verbose_name='名字')),
                ('extension', models.CharField(max_length=10, verbose_name='分機')),
                ('email', models.CharField(max_length=100, verbose_name='電子郵件')),
                ('jobtitle', models.CharField(db_column='jobTitle', max_length=50, verbose_name='職稱')),
                ('reportsto', models.ForeignKey(blank=True, db_column='reportsTo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.employees', verbose_name='匯報對象')),
                ('officecode', models.ForeignKey(db_column='officeCode', on_delete=django.db.models.deletion.DO_NOTHING, to='orders.offices', verbose_name='辦公室代碼')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customernumber', models.IntegerField(db_column='customerNumber', primary_key=True, serialize=False, verbose_name='客戶編號')),
                ('customername', models.CharField(db_column='customerName', max_length=50, verbose_name='客戶名稱')),
                ('contactlastname', models.CharField(db_column='contactLastName', max_length=50, verbose_name='聯絡人姓氏')),
                ('contactfirstname', models.CharField(db_column='contactFirstName', max_length=50, verbose_name='聯絡人名字')),
                ('phone', models.CharField(max_length=50, verbose_name='電話')),
                ('addressline1', models.CharField(db_column='addressLine1', max_length=50, verbose_name='地址1')),
                ('addressline2', models.CharField(blank=True, db_column='addressLine2', max_length=50, null=True, verbose_name='地址2')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='州')),
                ('postalcode', models.CharField(blank=True, db_column='postalCode', max_length=15, null=True, verbose_name='郵遞區號')),
                ('country', models.CharField(max_length=50, verbose_name='國家')),
                ('creditlimit', models.DecimalField(blank=True, db_column='creditLimit', decimal_places=2, max_digits=10, null=True, verbose_name='信用額度')),
                ('salesrepemployeenumber', models.ForeignKey(blank=True, db_column='salesRepEmployeeNumber', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.employees', verbose_name='銷售代表員工編號')),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('ordernumber', models.IntegerField(db_column='orderNumber', primary_key=True, serialize=False, verbose_name='訂單編號')),
                ('orderdate', models.DateField(db_column='orderDate', verbose_name='訂單日期')),
                ('requireddate', models.DateField(db_column='requiredDate', verbose_name='要求日期')),
                ('shippeddate', models.DateField(blank=True, db_column='shippedDate', null=True, verbose_name='發貨日期')),
                ('status', models.CharField(max_length=15, verbose_name='狀態')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='評論')),
                ('customernumber', models.ForeignKey(db_column='customerNumber', on_delete=django.db.models.deletion.DO_NOTHING, to='orders.customers', verbose_name='客戶編號')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productcode', models.CharField(db_column='productCode', max_length=1, primary_key=True, serialize=False, verbose_name=' 產品代碼')),
                ('productname', models.CharField(db_column='productName', max_length=70, verbose_name='產品名稱')),
                ('productscale', models.CharField(db_column='productScale', max_length=10, verbose_name='產品比例')),
                ('productvendor', models.CharField(db_column='productVendor', max_length=50, verbose_name='產品供應商')),
                ('productdescription', models.TextField(db_column='productDescription', verbose_name='產品描述')),
                ('quantityinstock', models.SmallIntegerField(db_column='quantityInStock', verbose_name='庫存數量')),
                ('buyprice', models.DecimalField(db_column='buyPrice', decimal_places=2, max_digits=10, verbose_name='購買價格')),
                ('msrp', models.DecimalField(db_column='MSRP', decimal_places=2, max_digits=10, verbose_name='建議零售價')),
                ('productline', models.ForeignKey(db_column='productLine', on_delete=django.db.models.deletion.DO_NOTHING, to='orders.productlines', verbose_name='產品線')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityordered', models.IntegerField(db_column='quantityOrdered', verbose_name='訂購數量')),
                ('priceeach', models.DecimalField(db_column='priceEach', decimal_places=2, max_digits=10, verbose_name='單價')),
                ('orderlinenumber', models.SmallIntegerField(db_column='orderLineNumber', verbose_name='訂單行號')),
                ('ordernumber', models.ForeignKey(db_column='orderNumber', on_delete=django.db.models.deletion.DO_NOTHING, to='orders.orders', verbose_name='訂單編號')),
                ('productcode', models.ForeignKey(db_column='productCode', on_delete=django.db.models.deletion.DO_NOTHING, to='orders.products', verbose_name='產品代碼')),
            ],
            options={
                'verbose_name': 'DomServer Contest 考區',
                'verbose_name_plural': 'DomServer Contest 考區',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('customernumber', models.OneToOneField(db_column='customerNumber', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='orders.customers', verbose_name='客戶編號')),
                ('checknumber', models.CharField(db_column='checkNumber', max_length=50, verbose_name='支票號碼')),
                ('paymentdate', models.DateField(db_column='paymentDate', verbose_name='付款日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金額')),
            ],
            options={
                'db_table': 'payments',
                'unique_together': {('customernumber', 'checknumber')},
            },
        ),
        migrations.AddConstraint(
            model_name='orderdetails',
            constraint=models.UniqueConstraint(fields=('ordernumber', 'productcode'), name='ordernumber_productcode'),
        ),
    ]
