# Generated by Django 5.0.6 on 2024-06-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'permissions': [('can_view_customers', 'Can view customers'), ('can_view_employees', 'Can view employees'), ('can_view_offices', 'Can view offices')],
            },
        ),
    ]
